### PR TITLE
API version setting

### PR DESCRIPTION
**Pull request by jolny**
The plugin didn't work with Subsonic 5.3, and the same should apply for any Subsonic version older than 6.2 so I added a setting for API version in the config file. Default version is currently "1.14.0", which is the 6.2 version.

### CODE REVIEW

**Comment by jolny** [comment]
Realized there's one more small fix left for the Search thing, don't merge yet. :)

**Comment by Prior99** [comment]
Hi, sorry for being so unresponsive. I am currently experiencing medical issues. I will try to have a look at this as soon as I can be back at my workstation.

**Comment by jolny** [comment]
No rush, man! Hope you get well soon. I'll see if I can find more improvements in the mean time :)
The "Search optimization" I mention here is that it's preferrable to use search3 instead of search2, when it is supported. This is because it sorts on ID3, which should give better results.
I'm also having some weird issues when searching, but they're caused by the Subsonic API. Getting some nonsense IDs on results.

**Comment by hhm0** [comment]
I hope you feel completely better soon, @Prior99 :-)

**Pull request merged**
